### ISSUE TITLE
Invalid version specified

### ISSUE THREAD

**Issue by r-wettstaedt** [dreamhouseapp/dreamhouse-lwc#15]
Following the instructions to install Dreamhouse using Salesforce DX, I am only getting to 5. Push the app to your scratch org.

```
$ sfdx force:source:push

PROJECT PATH  ERROR
────────────  ──────────────────────────────
N/A           Invalid version specified:45.0
```

Using a lower version, e.g. 44.0, returns even more errors.

```
$ sfdx --version
sfdx-cli/6.49.0 (darwin-x64) node-v10.13.0
```

**Comment by muenzpraeger** [comment]
What's the output of `sfdx plugins --core`?

**Comment by r-wettstaedt** [comment]
@muenzpraeger thank you for your swift response. I just realized it was my bad. sfdx was connected to the wrong org. It is working now.
