### ISSUE TITLE
Can't install any of the "trailheadapps" using the unlocked package install link once another trailheadapp is installed

### ISSUE THREAD

**Issue by jasonerivera** [dreamhouseapp/dreamhouse-lwc#21]
Getting the following error when trying ot install any of the trailheadapps apps once one of them is already installed in my dev org:

Package: LWCRecipes (04tB0000000KAfT)
Error Number: 439019472-181616 (1432842097)
Problem:

1. You can’t remove the following public properties: pageNumber,pageSize,totalItemCount, because the component is part of a managed package.
: You can’t remove the following public properties: pageNumber,pageSize,totalItemCount, because the component is part of a managed package.

**Comment by muenzpraeger** [comment]
Yes, that's expected. You can't overwrite similar named components from package a with package b.

**Comment by williamycxue** [comment]
Hi @muenzpraeger , sorry to bring up an old post. 

I have a similar issue as @jasonerivera  (You can’t remove the following public properties xxxxx) and I hope to get your opinion on how this can be resolved. 

In our case a version of the unlocked package was installed to a Org that includes a LWC with a @api property called "PropertyA". Then in the next version of the package, I have removed that @api "PropertyA" from the component. When I tried to install that new version of the package to the same Org, I was getting the same error message as described here.

What is your suggestion on managing the removal of @api properties in LWC between package versions?

**Comment by zaynelt** [comment]
Hi @williamycxue, you'll need to use the --upgradetype flag when installing the next package version(s). It tells the platform what to do with metadata changes. You can see the details about the usage here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_install_pkg_upgrade.htm

**Comment by williamycxue** [comment]
Thank you very much for your help @zaynelt !
