### ISSUE TITLE
Push problem

### ISSUE THREAD

**Issue by abrjpyAlmbrand** [dreamhouseapp/dreamhouse-lwc#9]
I get 

"Unexpected file found in package directory: /Users/.../lwc/dreamhouse-lwc/force-app/main/default/applications/Dreamhouse.app-meta.xml."

when i try to  do : sfdx force:source:push

What am i doing wrong?

**Comment by muenzpraeger** [comment]
There’s a known bug with the CLI if you have a parent folder with the name “lwc”, relative to your DX project.

Rename that folder, and you should be good.

**Comment by abrjpyAlmbrand** [comment]
Works thank you!
